

#include "iaq.h"

//static I2C_HandleTypeDef iaqi2ch;
extern I2C_HandleTypeDef hi2c1;

	void iAQ_Core_init(void)
	{
/*    iaqi2ch.Instance = I2Cx;
    iaqi2ch.Init.ClockSpeed = 100000;
    iaqi2ch.Init.DutyCycle = I2C_DUTYCYCLE_2;
    iaqi2ch.Init.OwnAddress1 = 0;
    iaqi2ch.Init.AddressingMode = I2C_ADDRESSINGMODE_7BIT;
    iaqi2ch.Init.DualAddressMode = I2C_DUALADDRESS_DISABLE;
    iaqi2ch.Init.OwnAddress2 = 0;
    iaqi2ch.Init.GeneralCallMode = I2C_GENERALCALL_DISABLE;
    iaqi2ch.Init.NoStretchMode = I2C_NOSTRETCH_DISABLE;
     Enable the remapping of Pins 6/7 to 8/9 and the I2C clock before the
     * initialization of the GPIO Pins in HAL_I2C_Init(). This is a fix of the
     * code generated by CubeMX v4.16.0
	
//    __HAL_AFIO_REMAP_I2C1_ENABLE();
//    __HAL_RCC_I2C1_CLK_ENABLE();
//    HAL_I2C_Init(&hi2c1);
	
	  if(HAL_I2C_Init(&iaqi2ch) != HAL_OK)
		{
			 Initialization Error
			while(1)
			{
			}
		}*/

	}

	



iAQ_Core_status_t iAQ_Core_GetNewReading(uint16_t* pred, uint16_t* status,
                               uint32_t* resistance, uint16_t* Tvoc) {
	uint8_t     cmd[9]    =   { 0 };
	uint32_t aux       =   0;


	/* Get the data */
	aux = HAL_I2C_Master_Receive(&hi2c1, IAQ_ADDRESS, &cmd[0], sizeof( cmd )/sizeof( cmd[0] ), HAL_MAX_DELAY);


	/* Update the parameters    */
	*pred         =  ( ( cmd[0] << 8 ) + cmd[1] );                           // Prediction = ( byte0 * 2^8 ) + byte1
	*status       =  ( iAQ_Core_status_flag_t )cmd[2];
	*resistance   =  ( ( cmd[4] << 16 ) + ( cmd[5] << 8 ) + cmd[6] );        // Resistance = ( byte4 * 2^16 ) + ( byte5 * 2^8 ) + byte6
	*Tvoc         =  ( ( cmd[7] << 8 ) + cmd[8] );                           // Tvoc       = ( byte7 * 2^8 ) + byte8




	if ( aux == I2C_SUCCESS )
		return   iAQ_Core_SUCCESS;
	else
		return   iAQ_Core_FAILURE;
}


